name: Contributing to the Contributors

on: [push]

jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Updating README.md
        run: python main.py
        env:
          REPO_NAME: '${{github.repository}}'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTRIBUTOR: '### Contributors'
          ENDCONTRIBUTOR: '---'
          FILEPATH: '/README.md'
          COLUMN_PER_ROW: '4'
          IMG_WIDTH: '50'
          FONT_SIZE: '14'
          COMMIT_MESSAGE: 'Contributed to the README.md'
